[build]
  publish = "_site"
  command = "npm run build"

# Redirección para SPA del admin.
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Página 404 personalizada.
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
